// Support Ticket Dashboard の演習用データです。
// チケット、社名、担当者名、メモはすべて架空のものであり、実在の組織、個人、案件とは関係ありません。
// internalMemo は社内限定情報を想定した項目です。具体値を Copilot Chat へ貼り付けないでください。
const tickets = [
  {
    id: "T-1001",
    title: "ログイン時に認証コードが届かない",
    customer: "青空商事",
    description: "管理者アカウントの認証コードがメールで受信できません。",
    status: "open",
    priority: "high",
    assignee: "佐藤",
    channel: "email",
    slaHours: 24,
    customerTier: "enterprise",
    createdAt: "2026-07-08",
    dueDate: "2026-07-12",
    internalMemo: "DEMO ONLY: 連絡先や契約情報はCRMで確認する。プロンプトには貼り付けない。"
  },
  {
    id: "T-1002",
    title: "請求書の宛名を変更したい",
    customer: "北斗デザイン",
    description: "今月分の請求書から新しい法人名を使用したいです。",
    status: "in-progress",
    priority: "medium",
    assignee: "田中",
    channel: "phone",
    slaHours: 72,
    customerTier: "standard",
    createdAt: "2026-07-09",
    dueDate: "2026-07-18",
    internalMemo: "DEMO ONLY: 請求先変更は承認フローを確認する。個別契約条件は貼り付けない。"
  },
  {
    id: "T-1003",
    title: "CSV エクスポートで文字化けする",
    customer: "みなと物流",
    description: "顧客一覧を CSV で開くと日本語が文字化けします。",
    status: "open",
    priority: "high",
    assignee: "鈴木",
    channel: "web",
    slaHours: 48,
    customerTier: "enterprise",
    createdAt: "2026-07-10",
    dueDate: "2026-07-14",
    internalMemo: "DEMO ONLY: サンプルCSVは社内共有フォルダーの架空データを使う。実データは使わない。"
  },
  {
    id: "T-1004",
    title: "メンバー追加方法について",
    customer: "山川製作所",
    description: "新入社員をプロジェクトに招待する手順を知りたいです。",
    status: "closed",
    priority: "low",
    assignee: "山本",
    channel: "email",
    slaHours: 96,
    customerTier: "standard",
    createdAt: "2026-07-02",
    dueDate: "2026-07-10",
    internalMemo: "DEMO ONLY: 解決済み。追加対応なし。"
  },
  {
    id: "T-1005",
    title: "ダッシュボードの表示が遅い",
    customer: "オレンジ出版",
    description: "午前中にレポート画面を開くと30秒ほどかかります。",
    status: "in-progress",
    priority: "high",
    assignee: "佐藤",
    channel: "web",
    slaHours: 24,
    customerTier: "enterprise",
    createdAt: "2026-07-11",
    dueDate: "2026-07-16",
    internalMemo: "DEMO ONLY: パフォーマンス計測ログは匿名化したサンプルだけを使う。"
  },
  {
    id: "T-1006",
    title: "二要素認証を無効にしたい",
    customer: "星野フーズ",
    description: "端末変更のため一時的に二要素認証を解除したいです。",
    status: "open",
    priority: "medium",
    assignee: "伊藤",
    channel: "phone",
    slaHours: 48,
    customerTier: "standard",
    createdAt: "2026-07-12",
    dueDate: "2026-07-20",
    internalMemo: "DEMO ONLY: 本人確認手順の詳細は社内手順書を参照。ここには記載しない。"
  },
  {
    id: "T-1007",
    title: "完了したタスクを復元したい",
    customer: "若葉システム",
    description: "誤って完了にしたタスクを未完了へ戻せますか。",
    status: "closed",
    priority: "low",
    assignee: "田中",
    channel: "email",
    slaHours: 96,
    customerTier: "standard",
    createdAt: "2026-07-05",
    dueDate: "2026-07-11",
    internalMemo: "DEMO ONLY: 操作履歴の詳細は顧客固有情報を含むため貼り付けない。"
  },
  {
    id: "T-1008",
    title: "API の利用上限を確認したい",
    customer: "西町テクノ",
    description: "現在のプランで利用できる API 呼び出し回数を教えてください。",
    status: "in-progress",
    priority: "medium",
    assignee: "鈴木",
    channel: "web",
    slaHours: 72,
    customerTier: "enterprise",
    createdAt: "2026-07-13",
    dueDate: "2026-07-22",
    internalMemo: "DEMO ONLY: 契約IDは <REDACTED> として扱う。"
  },
  {
    id: "T-1009",
    title: "通知メールが多すぎる",
    customer: "グリーン不動産",
    description: "コメントごとの通知をまとめて受け取る設定はありますか。",
    status: "open",
    priority: "low",
    assignee: "山本",
    channel: "email",
    slaHours: 96,
    customerTier: "standard",
    createdAt: "2026-07-13",
    dueDate: "2026-07-25",
    internalMemo: "DEMO ONLY: 通知設定のスクリーンショットは個人情報をマスクして扱う。"
  },
  {
    id: "T-1010",
    title: "削除したユーザーの履歴が見たい",
    customer: "ひかり会計",
    description: "退職者が更新した過去の操作履歴を確認したいです。",
    status: "open",
    priority: "medium",
    assignee: "伊藤",
    channel: "phone",
    slaHours: 48,
    customerTier: "standard",
    createdAt: "2026-07-14",
    dueDate: "2026-07-21",
    internalMemo: "DEMO ONLY: 監査ログは権限確認後に扱う。顧客名以外の詳細は貼り付けない。"
  },
  {
    id: "T-1011",
    title: "モバイル画面でボタンが隠れる",
    customer: "さくら旅行",
    description: "スマートフォンで予約ボタンが画面下部に隠れます。",
    status: "in-progress",
    priority: "high",
    assignee: "佐藤",
    channel: "web",
    slaHours: 24,
    customerTier: "enterprise",
    createdAt: "2026-07-14",
    dueDate: "2026-07-17",
    internalMemo: "DEMO ONLY: 画面キャプチャは架空アカウントで取得する。"
  },
  {
    id: "T-1012",
    title: "契約プランの変更について",
    customer: "中央リサーチ",
    description: "来月からチームプランへ変更する場合の料金を確認したいです。",
    status: "closed",
    priority: "low",
    assignee: "鈴木",
    channel: "email",
    slaHours: 96,
    customerTier: "standard",
    createdAt: "2026-07-06",
    dueDate: "2026-07-13",
    internalMemo: "DEMO ONLY: 見積条件はサンプル。実際の契約条件は貼り付けない。"
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = tickets;
}
